name: Deploy to HostGator

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false # Força não buscar submódulos para evitar erro

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clean Install Dependencies
        run: |
          rm -f package-lock.json
          npm install

      - name: Build project
        run: npm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./ # Se o usuário for 'DigPassagem@...', provavelmente já cai na pasta certa
          protocol: ftp
          port: 21
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
